# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: QAssist Documentation
site_url: https://qassist.io
copyright: Copyright &copy; 2024 QAssist Ltd
extra:
  homepage: https://qassist.io
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/QAssistio
    - icon: fontawesome/brands/github
      link: https://github.com/qassistio
extra_css:
  - stylesheets/extra.css
nav:
  - Welcome: index.md
  - Machines:
      - machines/setup-machine.md
  - Advanced Usage:
    - Bridges:
        - bridges/public-bridges.md
        - bridges/setup-bridge.md
    - Cloud Providers:
        - cloud-providers/index.md
        - cloud-providers/preparing-aws.md
        - cloud-providers/preparing-azure.md
  - Additional Help:
      - help/raise-a-ticket.md
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  language: en
  favicon: assets/icons/favicon.ico
  logo: assets/img/icon.png
  features:
    - navigation.path
    - navigation.expand
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Nunito
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
